# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-09 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldbuilder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='value',
            field=models.CharField(default='please Set a Name', max_length=200),
        ),
        migrations.AddField(
            model_name='variable',
            name='variable_name',
            field=models.CharField(default='please Set a Name', max_length=200),
        ),
    ]
