# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-09 16:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worldbuilder', '0002_auto_20160109_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='entry_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='variable',
            old_name='variable_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='world',
            old_name='world_name',
            new_name='name',
        ),
    ]
