# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-09 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldbuilder', '0003_auto_20160109_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='name',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='variable',
            name='value',
            field=models.CharField(default='-', max_length=200),
        ),
    ]
