# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 22:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('worldbuilder', '0004_auto_20160109_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
